[package]
name = "sqlx-bench"
version = "0.1.0"
authors = ["Austin Bonander <austin@launchbadge.com>"]
edition = "2018"
publish = false

[features]
runtime-actix = ["sqlx/runtime-actix", "sqlx-rt/runtime-actix"]
runtime-async-std = ["sqlx/runtime-async-std", "sqlx-rt/runtime-async-std"]
runtime-tokio = ["sqlx/runtime-tokio", "sqlx-rt/runtime-tokio"]

postgres = ["sqlx/postgres"]

[dependencies]
criterion = "0.3.3"
dotenv = "0.15.0"
once_cell = "1.4"
sqlx = { version = "0.4.0-beta.1", path = "../", default-features = false }
sqlx-rt = { version = "0.1.1", path = "../sqlx-rt", default-features = false }

[[bench]]
name = "pg_pool"
harness = false
required-features = ["postgres"]
